const skillAliases: Record<string, string> = {
  'react': 'React',
  'reactjs': 'React',
  'react.js': 'React',
  'vue': 'Vue.js',
  'vuejs': 'Vue.js',
  'vue.js': 'Vue.js',
  'node': 'Node.js',
  'nodejs': 'Node.js',
  'node.js': 'Node.js',
  'next': 'Next.js',
  'nextjs': 'Next.js',
  'next.js': 'Next.js',
  'nuxt': 'Nuxt',
  'nuxtjs': 'Nuxt',
  'nuxt.js': 'Nuxt',
  'angular': 'Angular',
  'angularjs': 'Angular',
  'typescript': 'TypeScript',
  'ts': 'TypeScript',
  'javascript': 'JavaScript',
  'js': 'JavaScript',
  'tailwind': 'Tailwind CSS',
  'tailwindcss': 'Tailwind CSS',
  'tailwind css': 'Tailwind CSS',
  'postgres': 'PostgreSQL',
  'postgresql': 'PostgreSQL',
  'mongo': 'MongoDB',
  'mongodb': 'MongoDB',
  'graphql': 'GraphQL',
  'csharp': 'C#',
  'c#': 'C#',
  'dotnet': '.NET',
  '.net': '.NET',
  'sass': 'Sass',
  'scss': 'Sass',
  'rest': 'REST API',
  'restapi': 'REST API',
  'rest api': 'REST API',
  'cicd': 'CI/CD',
  'ci/cd': 'CI/CD',
  'react native': 'React Native',
  'reactnative': 'React Native',
  'html': 'HTML',
  'css': 'CSS',
  'python': 'Python',
  'java': 'Java',
  'php': 'PHP',
  'ruby': 'Ruby',
  'go': 'Go',
  'rust': 'Rust',
  'swift': 'Swift',
  'kotlin': 'Kotlin',
  'flutter': 'Flutter',
  'svelte': 'Svelte',
  'sql': 'SQL',
  'docker': 'Docker',
  'kubernetes': 'Kubernetes',
  'aws': 'AWS',
  'gcp': 'GCP',
  'azure': 'Azure',
  'git': 'Git',
  'linux': 'Linux',
}

export function normalizeSkillName(name: string): string {
  const trimmed = name.trim()
  if (!trimmed) return trimmed
  const key = trimmed.toLowerCase()
  return skillAliases[key] || trimmed
}
